apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientapp-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clientapp-pod
  template:
    metadata:
      labels:
        app: clientapp-pod
    spec:
      containers:
        - name: clientapp-container
          image: clientapp-image
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: clientapp-service
spec:
  type: LoadBalancer 
  selector:
    app: clientapp-pod
  ports:
  - port: 8080