name: Build App

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-flask-app . -t test-image &> build_log.txt

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          pip install openai

      - name: Generate Error Suggestion
        env:
          OPEN_AI_KEY: ${{ secrets.OPEN_AI_KEY }}
        if: failure()
        run: |
          python .github/scripts/build-error-suggestions.py build_log.txt
